# Generated by Django 3.1.7 on 2021-02-28 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('brand', models.CharField(choices=[('mufti', 'Mufti'), ('park_avenue', 'Park Avenue'), ('levis', "Levi's"), ('pepe_jeans', 'Pepe Jeans'), ('peter_england', 'Peter England'), ('biba', 'Biba'), ('flying_machine', 'Flying Machine'), ('raymond', 'Raymond'), ('max', 'Max'), ('adidas', 'Adidas'), ('nike', 'Nike')], max_length=100)),
                ('category', models.CharField(choices=[('kids', 'Kids'), ('babies', 'Babies'), ('men', 'Men'), ('women', 'Women'), ('winter', 'Winter Cloths')], max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50)),
                ('occasion', models.CharField(blank=True, choices=[('CASUAL', 'CASUAL'), ('CLUB_CASUAL', 'CLUB CASUAL'), ('BUSINESS_CASUAL', 'BUSINESS CASUAL'), ('regular', 'Regular')], max_length=50)),
                ('material', models.CharField(choices=[('cotton', 'Cotton'), ('silk', 'Silk'), ('linen', 'Linen'), ('wool', 'Wool'), ('leather', 'Leather'), ('nylon', 'Nylon'), ('velvet', 'Velvet'), ('denim', 'Denim')], max_length=50)),
                ('size', models.CharField(choices=[('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], max_length=3)),
                ('color', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='media/products/%Y/%m')),
                ('quantity', models.IntegerField()),
                ('quanity_sell', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('discount_percentage', models.FloatField()),
                ('is_featured', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
